# Generated by Django 2.2 on 2020-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qno',
            field=models.IntegerField(unique=True),
        ),
    ]
